// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsimeggbjabgwetxqavt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzaW1lZ2diamFiZ3dldHhxYXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDI2MjYsImV4cCI6MjA2ODg3ODYyNn0.sD0C6w97hPUJsJCjomLH4X90eSe6lzImMMyY280KK5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});